version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: my-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/postgres
    command: >
      bash -c "
      sleep 10 &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email a@b.com
      "

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
    command: airflow scheduler